### ISSUE TITLE
How to understand this extension

### ISSUE THREAD

**Issue by js0701** [WICG/img-conversion#6]
Hi, This is Johnson from Crosswalk.
Please help me to understand this extension.
Per my understanding,  the extension just for simplify the Blob to Image Data conversion.
The sync/unsync problem only exist for some browser(or Web Engine). If decoding is happening before img.onload instead of in ctx.getImageData, then the internal process of these 2 flow (original vs the new method you provide here) are identical.
Please correct me if I am wrong. THX

**Comment by AshleyScirra** [comment]
AFAIK, no browser engines decode in img.onload, because doing so runs contrary to lazy loading principles. It would mean images that are downloaded but not used still get decoded, wastefully consuming memory and CPU time. Therefore browsers synchronously decode images the first time they are used.

Even if browsers did wastefully decode images in the onload event, this spec still enables new async use cases, such as converting ImageData back to a Blob.

**Comment by js0701** [comment]
@AshleyScirra  Thanks for the answer.  I noticed that the original define for ImageData is

interface ImageData {
  readonly attribute unsigned long width;
  readonly attribute unsigned long height;
  readonly attribute Uint8ClampedArray data;
};

Why we don't include those 3 read only attribute in the new definition?

**Comment by js0701** [comment]
@AshleyScirra  As you have explained,

Then I think something in the example should be changed?
function BlobToImageData(blob)
{
        let blobUrl = URL.createObjectURL(blob);

```
    return new Promise((resolve, reject) =>
    {
            let img = new Image();
            img.onload = () => resolve(img); //Johnson: Image.onload does not decode,  We can only resolve it after we have decoded the img, We can have something like img.decoded =()=> resolve(img)?

            img.onerror = err => reject(err);
            img.src = blobUrl;
    }).then(img =>
    {
            URL.revokeObjectURL(blobUrl);

            let w = img.width;
            let h = img.height;

            let canvas = document.createElement("canvas");
            canvas.width = w;
            canvas.height = h;
            let ctx = canvas.getContext("2d");
            ctx.drawImage(img, 0, 0);
            return ctx.getImageData(0, 0, w, h);    // some browsers synchronously decode image here
    });
```

};

**Comment by js0701** [comment]
In the above example, I am meaning something like the internal process of the new flow

**Comment by AshleyScirra** [comment]
@js0701 - it is a partial interface so it only specifies new properties and methods, not the existing ones. I think we will add more description in the explainer document (issue #1).

**Comment by AshleyScirra** [comment]
Added explainer.md, hopefully that clears it up.
